### PR TITLE
Example and warning cleanup

### PR DESCRIPTION
**Pull request by kenamis**
I put all the example scripts in their own namespace "NobleMuffins.LimbHacker.Examples".  A lot of their class names conflict with Unity class names.

There were two warnings that I fixed too.  The "unused" event, I add a pragma to disable that warning and an additional compiler directive for newer Unity versions for the "animator.GetCurrentAnimatorStateInfo(0).fullPathHash"

Lastly, I made destructionPending protected instead of private so we could inherit from hackable for an UMA integration.

### CODE REVIEW

**Comment by JoeCooper** [comment]
Thanks!

**Comment by JoeCooper** [comment]
I’m working on this now.

So basically LH has this kind of inner core in ThreadSafeSlice which is given a mesh, and yields two meshes. This result is marshaled back to the event dispatch thread which manipulates the view graph.

This doesn’t work for you.

You need:

1) Minimal affect on the view graph; you will do that according to your own plan.
2) One mesh product instead of two.
3) Divorce vertices from bones on the “other” side of the slice.

I’m going to make a branch and do this there.

I will need to work a little into it before I can tell you the cost, but if we can’t come to an agreement, we can drop it safely even if I’ve done some work on it. (“Speculative Execution”)

I’ll try to get some visible progress for you within some hours.

- Joe

**Comment by kenamis** [comment]
That sounds good to me.

The main issue I was running in to was in LimbHackerAgent->consumeJobYield
where is clones the original object.
Cloning the original causes issues with all the other components on it, and
we can't really use the alternate prefabs because the UMA object is built
at runtime.
Now that I think about it, I probably could have a runtime hook up to the
alternatePrefabs that is a stripped down version of the runtime built UMA.
Do you think that would be easier to do (or even work) or better to proceed
with the idea you had above?

**Comment by JoeCooper** [comment]
Actually it could. If you rummage around in there you can replace the code with your own and produce any secondary you want.

The code you’re looking for is lines 107 to 117 in LimbHackerAgent.

It decides if it can continue using the original as the “bravo” object then produces an “Alfa” object based on either the original or the alt.

Try it and tell me how it works for you. Let me know then if you still need the refactor discussed previously.

Good luck!

**Pull request merged**
